### ISSUE TITLE
Performance issue with complicated loops in function

### ISSUE THREAD

**Issue by zhangcx93** [JuliaGPU/CUDA.jl#984] opened 2021-06-15 14:10 UTC
**Describe the bug**
When I'm running my script, I found that the first time run of the main function containing for loop is unreasonably slow.
By putting the code outside of the main function to the global makes the first step in loop much faster and the following step the same as warmed up code.

**To reproduce**

The Minimal Working Example (MWE) for this bug:

```julia
using CUDA
using Statistics

function some_func(x, y)
    a = CUDA.rand(1000)
    b = CUDA.rand(1000)
    c = a .* b
    return c .* x .* y
end

function main()
    result = []
    count = 0
    for i in 1:3
        t = time()
        for j in 0:20
            for k in 1:20
                count += 1
                for m in 1:20
                    a = CUDA.rand(1000)
                    b = CUDA.rand(1000)
                    c = some_func(a, b)
                    push!(result, mean(c))
                end
            end
        end
        println(time() - t)
    end
end

main()
```

The printed timing is
First time:
```
42.087000131607056
33.35199999809265
34.365999937057495
```

Second time:
```
1.1009998321533203
0.8480000495910645
1.4190001487731934
```

Without main, just global loop
```
10.562000036239624
0.935999870300293
1.316999912261963
```

**Expected behavior**

The top loop in main should be around 10s for the first step and around 1s for the following, but not 42s for the first step and around 33s for the following step. 42s and 33s are too much for compilation here.

**Version info**

Details on Julia:

```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_GPU_ALLOWSCALAR = false
```

Details on CUDA:

```
CUDA toolkit 11.3.1, artifact installation
CUDA driver 11.3.0
NVIDIA driver 466.77.0

Libraries:
- CUBLAS: 11.5.1
- CURAND: 10.2.4
- CUFFT: 10.4.2
- CUSOLVER: 11.1.2
- CUSPARSE: 11.6.0
- CUPTI: 14.0.0
- NVML: 11.0.0+466.77
- CUDNN: 8.20.0 (for CUDA 11.3.0)
- CUTENSOR: 1.3.0 (for CUDA 11.2.0)

Toolchain:
- Julia: 1.6.1
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device capability support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

1 device:
  0: NVIDIA GeForce RTX 2080 Ti (sm_75, 8.582 GiB / 11.000 GiB available)
```

**Comment by zhangcx93** [comment] 2021-06-15 14:23
The CPU version of the same code's timing is:
First time
```
0.2480001449584961
0.21000003814697266
0.20399999618530273
```
Second time
```
0.20300006866455078
0.20399999618530273
0.21299982070922852
```

This indicates there might be something wrong with loop with CUDA... I think these code are GPU friendly and the size is not too small...

**Comment by maleadt** [comment] 2021-06-15 15:20
That's because Julia interprets code when it's at the top level, whereas if you put it in a function you 'force' compilation.

**Comment by zhangcx93** [comment] 2021-06-15 15:36
Well, if you try to rewrite the code in CPU version, you'll find that even been put into a function, as "force compilation mode", the second and following step is much faster than the first time(same as what you'll get from @btime), while the first step is doing heavy compilation.
And if the top level code is pure interpreted, how the second and following step the same speed as compiled code and only the first time in loop is slow?

**Comment by zhangcx93** [comment] 2021-06-15 15:41
Also the compilation time should not scale with the length of the loop right?

**Comment by stillyslalom** [comment] 2021-06-15 15:44
There does appear to be a regression here (xref from [Discourse](https://discourse.julialang.org/t/how-to-loop-in-script-properly-perhaps-cuda-specific/62939/11?u=stillyslalom)).

On CUDA.jl v3.1.0, 
```
julia> main() # first run
29.039000034332275
1.7300000190734863
1.61899995803833
```
On v3.3.0,
```
julia> main() # first run
80.84599995613098
61.09299993515015
63.625

julia> main() # second run
1.5520000457763672
1.7239999771118164
1.375999927520752
```

**Comment by maleadt** [comment] 2021-06-15 15:45
Yeah, something seems off, even though this also seems compilation heuristic-related.

**Comment by zhangcx93** [comment] 2021-06-15 15:47
```
using CUDA

function some_func(x, y)
    a = CUDA.rand(1000)
    b = CUDA.rand(1000)
    c = a .* b
    return c .* x .* y
end

function main()
    N = 20
    a = CUDA.rand(1000)
    b = CUDA.rand(1000)
    for i in 1:N
        for j in 0:800
            c = some_func(a, b)
        end
    end
end

@time main()
@time main()
```
The compilation time should approximately be the diff between first and the second @time result, by changing the N value, you can see it's scaling with N... This should not happen.

**Comment by maleadt** [comment] 2021-06-15 15:50
Profiling this function reveals that all the time is spent in `eval` as called from Memoization.jl, and switching to that package was a recent change indeed. cc @marius311

```
./boot.jl:360, eval [inlined]
/home/tim/Julia/depot/packages/Memoization/6Lcw7/src/Memoization.jl:46, macro expansion [inlined]
/home/tim/Julia/depot/packages/Memoization/6Lcw7/src/Memoization.jl:42, MethodInstance for get_cache(::Type{IdDict}, ::typeof(CUDA.release))
/home/tim/Julia/depot/packages/Memoization/6Lcw7/src/Memoization.jl:125, soft_limit [inlined]
/home/tim/Julia/pkg/CUDA/src/pool.jl:111, MethodInstance for var"#actual_alloc#160"(::Bool, ::CuStream, ::typeof(CUDA.actual_alloc), ::Int64, ::Bool)
```

**Comment by marius311** [comment] 2021-06-15 17:12
Will take a look, that eval is only supposed to be called during warmup.

**Comment by marius311** [comment] 2021-06-15 21:22
@zhangcx93 There was indeed a bug in Memoization affecting your case, which I just fixed in the linked PR. See if `] add Memoization#f704c1f` fixes your issues (I checked your MWE and it does fix that). Will tag this version shortly, barring anything else popping up.

**Comment by zhangcx93** [comment] 2021-06-16 03:18
I installed the fix and it worked.

Btw in the second MWE, I found that the warm up step is allocating a lot of memory, it uses `19.84 M allocations: 1.059 GiB` during warming up and `3.20 M allocations: 106.953 MiB` after warmed up.
Is this a normal behavior?

**Comment by marius311** [comment] 2021-06-16 10:51
A new version is now tagged which should fix this issue (in a slightly different way than the above PR, so do let me know if something still happens, but I did double check your MWE). As for the memory allocations, I don't know about those exact numbers, but it's certainly pretty typical to get high memory usage on first call during precompilation, unrelated to either CUDA or Memoization. Is this more / something else than you'd expect from that?

**Comment by zhangcx93** [comment] 2021-06-16 11:45
After some experiments I found that the more than 1g allocation and about 6-7s happens only at the first compilation of any GPU code, and it seems constant. Maybe it's a hint there is a way to cache this so user will never see this consumption and delay more than once a lifetime?

Then the other question is that as pure GPU code, why it takes so many allocations to run... up to millions of times and hundreds of MiB for a simple program like this...

**Comment by maleadt** [comment] 2021-06-16 12:45
> more than 1g allocation and about 6-7s happens only at the first compilation of any GPU code

No?

```julia-repl
julia> using CUDA

julia> kernel() = (@cuprintln("1"); return)
kernel (generic function with 1 method)

julia> @time @cuda kernel()
  7.851168 seconds (23.33 M allocations: 1.331 GiB, 4.62% gc time, 0.08% compilation time)
1

julia> kernel() = (@cuprintln("2"); return)
kernel (generic function with 1 method)

julia> @time @cuda kernel()
  0.116106 seconds (204.56 k allocations: 12.150 MiB, 7.61% gc time, 77.25% compilation time)
2
```

**Comment by zhangcx93** [comment] 2021-06-16 12:50
What do you mean by "No?"
Your code is showing exactly what I said..?

**Comment by maleadt** [comment] 2021-06-16 13:02
> at the first compilation of any GPU code

I interpret that as: every time you compile any GPU code for the first time. Instead, the cost happens when **compiling the GPU compiler itself**, so it only happens for the very first kernel, and never again after that even if compiling new kernels.

So this is just the 'time to first plot' issue, nothing GPU specific. The fact that the GPU code is simple, or "pure" as you state it, doesn't help here.

**Comment by zhangcx93** [comment] 2021-06-16 13:23
According to [precompile_tutorial](https://julialang.org/blog/2021/01/precompile_tutorial/)
I just added a line of
```
precompile(ones, (Int, ))
```
at the bottom of CUDA.jl, it seems that "compiling the GPU compiler itself" is now successfully cached...

**Comment by zhangcx93** [comment] 2021-06-16 13:47
it's not working... i'm been naive...(I thought it's working because ones and rand is fast for some reason, these doesn't need to compile the compiler to run?)

**Comment by maleadt** [comment] 2021-06-16 14:04
No offense, but if it were as easy as a single precompile statement, we'd have done that long ago :slightly_smiling_face: But don't let that scare you, it would probably yield some good results if somebody had a good look at e.g. the SnoopCompile.jl tools (https://timholy.github.io/SnoopCompile.jl/stable/, https://julialang.org/blog/2021/01/snoopi_deep/) and optimize the CUDA.jl code.

About this issue, an update to Memoization.jl should have fixed it, so this can be closed.

**Closed as completed by maleadt** 2021-06-16 14:04 UTC
Labels: performance, regression
