### ISSUE TITLE
CUBLASError: the GPU program failed to execute

### ISSUE THREAD

**Issue by Martyn-R** [JuliaGPU/CUDA.jl#447] opened 2020-09-24 19:52 UTC
While running the AlphaZero connect-four tutorial (https://jonathan-laurent.github.io/AlphaZero.jl/dev/tutorial/connect_four/), I receive the following error message:

```ERROR: LoadError: CUBLASError: the GPU program failed to execute (code 13, CUBLAS_STATUS_EXECUTION_FAILED)```

The author of AlphaZero.jl asked me to report the error here.   The stack trace is at the end of this post.

**To reproduce**

Run the code below. After self-play in iteration 1 the error occurs. Unfortunately this takes about 1-2 hours.

```
git clone --branch v0.3.0 https://github.com/jonathan-laurent/AlphaZero.jl.git
cd AlphaZero.jl
julia --project -e "import Pkg; Pkg.instantiate()"
julia --project --color=yes scripts/alphazero.jl --game connect-four train
```
![image](https://user-images.githubusercontent.com/30200826/94192127-ce78a880-feae-11ea-9c8a-7c4310d99340.png)

**Version info**
```
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

```
CUDA toolkit 10.2.89, artifact installation
CUDA driver 10.2.0
NVIDIA driver 440.95.1

Libraries: 
- CUBLAS: 10.2.2
- CURAND: 10.1.2
- CUFFT: 10.1.2
- CUSOLVER: 10.3.0
- CUSPARSE: 10.3.1
- CUPTI: 12.0.0
- NVML: 10.0.0+440.95.1
- CUDNN: 8.0.2 (for CUDA 10.2.0)
- CUTENSOR: 1.2.0 (for CUDA 10.2.0)

Toolchain:
- Julia: 1.5.1
- LLVM: 9.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4
- Device support: sm_30, sm_32, sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

1 device:
  0: GeForce GTX 1070 Ti (sm_61, 7.322 GiB / 7.923 GiB available)

```

**Environment status**
```
Status `~/.julia/environments/v1.5/Project.toml`
  [fbb218c0] BSON v0.2.6
  [336ed68f] CSV v0.7.7
  [052768ef] CUDA v1.3.3
  [3895d2a7] CUDAapi v4.0.0
  [5ae59095] Colors v0.12.4
  [a93c6f00] DataFrames v0.21.7
  [587475ba] Flux v0.11.1 `https://github.com/FluxML/Flux.jl.git#master`
  [0c68f7d7] GPUArrays v5.2.1
  [61eb1bfa] GPUCompiler v0.6.1
  [47d2ed2b] Hyperscript v0.0.3
  [7073ff75] IJulia v1.21.3
  [6a3955dd] ImageFiltering v0.6.15
  [6218d12a] ImageMagick v1.1.6
  [916415d5] Images v0.22.4
  [c601a237] Interact v0.10.3
  [929cbde3] LLVM v2.0.0
  [38d8eb38] Lathe v0.1.1
  [eb30cadb] MLDatasets v0.5.2
  [d96e819e] Parameters v0.12.1
  [91a5bcdd] Plots v1.6.6
  [c3e4b0f8] Pluto v0.11.14
  [7f904dfe] PlutoUI v0.6.4
  [6f49c342] RCall v0.13.7
  [fd094767] Suppressor v0.2.0
  [8a913413] Survival v0.2.0
  [0f1e0344] WebIO v0.8.93


```

**Stack trace:**
```
ERROR: LoadError: CUBLASError: the GPU program failed to execute (code 13, CUBLAS_STATUS_EXECUTION_FAILED)
Stacktrace:
 [1] throw_api_error(::CUDA.CUBLAS.cublasStatus_t) at /home/martijn/.julia/packages/CUDA/dZvbp/lib/cublas/error.jl:47
 [2] macro expansion at /home/martijn/.julia/packages/CUDA/dZvbp/lib/cublas/error.jl:58 [inlined]
 [3] cublasSgemm_v2(::Ptr{Nothing}, ::Char, ::Char, ::Int64, ::Int64, ::Int64, ::Array{Float32,1}, ::CUDA.CuArray{Float32,2}, ::Int64, ::CUDA.CuArray{Float32,2}, ::Int64, ::Array{Float32,1}, ::CUDA.CuArray{Float32,2}, ::Int64) at /home/martijn/.julia/packages/CUDA/dZvbp/lib/utils/call.jl:93
 [4] gemm!(::Char, ::Char, ::Float32, ::CUDA.CuArray{Float32,2}, ::CUDA.CuArray{Float32,2}, ::Float32, ::CUDA.CuArray{Float32,2}) at /home/martijn/.julia/packages/CUDA/dZvbp/lib/cublas/wrappers.jl:721
 [5] gemm_wrapper!(::CUDA.CuArray{Float32,2}, ::Char, ::Char, ::CUDA.CuArray{Float32,2}, ::CUDA.CuArray{Float32,2}, ::Float32, ::Float32) at /home/martijn/.julia/packages/CUDA/dZvbp/lib/cublas/linalg.jl:188
 [6] mul! at /home/martijn/.julia/packages/CUDA/dZvbp/lib/cublas/linalg.jl:222 [inlined]
 [7] mul! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/matmul.jl:208 [inlined]
 [8] * at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/matmul.jl:160 [inlined]
 [9] (::Flux.Dense{typeof(NNlib.relu),CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,1}})(::CUDA.CuArray{Float32,2}) at /home/martijn/.julia/packages/Flux/05b38/src/layers/basic.jl:123
 [10] Dense at /home/martijn/.julia/packages/Flux/05b38/src/layers/basic.jl:134 [inlined]
 [11] applychain at /home/martijn/.julia/packages/Flux/05b38/src/layers/basic.jl:36 [inlined] (repeats 4 times)
 [12] (::Flux.Chain{Tuple{Flux.Conv{2,4,typeof(identity),CUDA.CuArray{Float32,4},CUDA.CuArray{Float32,1}},Flux.BatchNorm{typeof(NNlib.relu),CUDA.CuArray{Float32,1},CUDA.CuArray{Float32,1},Float32},typeof(Flux.flatten),Flux.Dense{typeof(NNlib.relu),CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,1}},Flux.Dense{typeof(tanh),CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,1}}}})(::CUDA.CuArray{Float32,4}) at /home/martijn/.julia/packages/Flux/05b38/src/layers/basic.jl:38
 [13] forward(::AlphaZero.FluxLib.ResNet{Game}, ::CUDA.CuArray{Float32,4}) at /home/martijn/AlphaZero.jl/src/networks/flux.jl:162
 [14] evaluate(::AlphaZero.FluxLib.ResNet{Game}, ::CUDA.CuArray{Float32,4}, ::CUDA.CuArray{Float32,2}) at /home/martijn/AlphaZero.jl/src/networks/network.jl:253
 [15] losses(::AlphaZero.FluxLib.ResNet{Game}, ::LearningParams, ::Float32, ::Float32, ::Tuple{CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,4},CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,2}}) at /home/martijn/AlphaZero.jl/src/learning.jl:62
 [16] learning_status(::AlphaZero.Trainer, ::Tuple{CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,4},CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,2}}) at /home/martijn/AlphaZero.jl/src/learning.jl:142
 [17] (::AlphaZero.var"#71#74"{AlphaZero.Trainer})(::Tuple{CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,4},CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,2},CUDA.CuArray{Float32,2}}) at ./none:0
 [18] iterate at ./generator.jl:47 [inlined]
 [19] collect(::Base.Generator{Base.Generator{Array{Tuple{Array{Float32,2},Array{Float32,4},Array{Float32,2},Array{Float32,2},Array{Float32,2}},1},AlphaZero.Util.var"#9#11"{AlphaZero.var"#70#73"{AlphaZero.Trainer}}},AlphaZero.var"#71#74"{AlphaZero.Trainer}}) at ./array.jl:686
 [20] learning_status(::AlphaZero.Trainer) at /home/martijn/AlphaZero.jl/src/learning.jl:157
 [21] learning_step!(::Env{Game,AlphaZero.FluxLib.ResNet{Game},NamedTuple{(:board, :curplayer),Tuple{StaticArrays.SArray{Tuple{7,6},UInt8,2,42},UInt8}}}, ::Session{Env{Game,AlphaZero.FluxLib.ResNet{Game},NamedTuple{(:board, :curplayer),Tuple{StaticArrays.SArray{Tuple{7,6},UInt8,2,42},UInt8}}}}) at /home/martijn/AlphaZero.jl/src/training.jl:170
 [22] macro expansion at ./timing.jl:310 [inlined]
 [23] macro expansion at /home/martijn/AlphaZero.jl/src/report.jl:229 [inlined]
 [24] train!(::Env{Game,AlphaZero.FluxLib.ResNet{Game},NamedTuple{(:board, :curplayer),Tuple{StaticArrays.SArray{Tuple{7,6},UInt8,2,42},UInt8}}}, ::Session{Env{Game,AlphaZero.FluxLib.ResNet{Game},NamedTuple{(:board, :curplayer),Tuple{StaticArrays.SArray{Tuple{7,6},UInt8,2,42},UInt8}}}}) at /home/martijn/AlphaZero.jl/src/training.jl:295
 [25] resume!(::Session{Env{Game,AlphaZero.FluxLib.ResNet{Game},NamedTuple{(:board, :curplayer),Tuple{StaticArrays.SArray{Tuple{7,6},UInt8,2,42},UInt8}}}}) at /home/martijn/AlphaZero.jl/src/ui/session.jl:383
 [26] top-level scope at /home/martijn/AlphaZero.jl/scripts/alphazero.jl:89
 [27] include(::Function, ::Module, ::String) at ./Base.jl:380
 [28] include(::Module, ::String) at ./Base.jl:368
 [29] exec_options(::Base.JLOptions) at ./client.jl:296
 [30] _start() at ./client.jl:506
in expression starting at /home/martijn/AlphaZero.jl/scripts/alphazero.jl:80

```

**Comment by maleadt** [comment] 2020-09-25 06:01
This is possible due to a bug in CUDA; from their 11.1 release notes:
```
Fixed an issue that caused an Address out of bounds error when calling cublasSgemm(). 
```

Does it reproduce consistently?

**Comment by Martyn-R** [comment] 2020-09-25 13:36
Seems consistent yes: five out of five times.   Do you recommend to upgrade to 11.1?

**Comment by maleadt** [comment] 2020-09-25 14:40
You can try to see if it fixes your problem, there's a PR here, but beware that (1) the current master branch of CUDA is slightly breaking, and (2) there's no CUDNN or CUTENSOR artifacts for CUDA 11.1 yet.

**Comment by maleadt** [comment] 2020-09-29 06:07
You can now try CUDA 11.1 with CUDA.jl#master by specifying `JULIA_CUDA_VERSION=11.1` in your environment

**Comment by deveshjawla** [comment] 2020-10-20 21:16
> You can now try CUDA 11.1 with CUDA.jl#master by specifying `JULIA_CUDA_VERSION=11.1` in your environment

```
JULIA_CUDA_VERSION=11.1 julia --project --color=yes scripts/alphazero.jl --game connect-four train
ERROR: LoadError: InitError: CUDA.jl does not yet support CUDA with nvdisasm 11.1.74; please file an issue.
```
Same issue.

I believe it is due to CUDA.jl v1.3.3 being incompatible with CUDA 11.1

**Comment by maleadt** [comment] 2020-10-23 06:55
> I believe it is due to CUDA.jl v1.3.3 being incompatible with CUDA 11.1

That's why I specified CUDA.jl#master; this option is only supported on v2.0 or more recent.

**Comment by deveshjawla** [comment] 2020-10-23 07:13
> > I believe it is due to CUDA.jl v1.3.3 being incompatible with CUDA 11.1
> 
> That's why I specified CUDA.jl#master; this option is only supported on v2.0 or more recent.

Yes but the problem is, Flux depends on CUDA.jlv1.3.3 as you also write before. I wonder if there is a way to make CUDA.jl#master work with Flux0.11.1.

**Comment by ToucheSir** [comment] 2020-10-25 18:49
@deveshjawla that's something to follow on the Flux side of things and not CUDA.jl. You could see if https://github.com/FluxML/Flux.jl/pull/1345 works for you (it's very WIP, but worth a try).

**Comment by maleadt** [comment] 2021-04-08 10:20
I'm going to close this for now, as it looks like an issue with CUDA. CUDA.jl now supports newer versions of the CUDA toolkit, and if this still happens on CUDA.jl 3.0 (soon to be released) with a compatible FLux release, please do open a new issue!

**Closed as completed by maleadt** 2021-04-08 10:20 UTC
Labels: bug, cuda array
