### ISSUE TITLE
Memory corruption / segfault with Threads.@async and planned FFTs 

### ISSUE THREAD

**Issue by marius311** [JuliaGPU/CUDA.jl#859] opened 2021-04-23 10:16 UTC
I'm finding occasional memory corruption / segfaults when doing a planned inverse real FFT from inside a `Threads.@async`. To reproduce:

```julia
using CUDA, FFTW

plan = plan_rfft(cu(rand(256,256)))
y = plan * cu(rand(256,256))

lastx = nothing
for i = 1:1000
    Threads.@sync Threads.@spawn global x = plan \ y
    CUDA.device_synchronize()
    if !isnothing(lastx) && lastx[1]!=x[1]
        error((lastx[1], x[1]))
    else
        lastx = x
    end
end
```

Sometimes it takes a few tries to trigger it. Either the code errors indicating a different result was obtained. Other times it segfaults with:

```
signal (11): Segmentation fault
in expression starting at REPL[9]:1
unknown function (ip: 0x2aaaef5bcb29)
unknown function (ip: 0x2aaaef5de0b3)
unknown function (ip: 0x2aaaef4c3049)
unknown function (ip: 0x2aaaef4c33fd)
cuLaunchKernel at /usr/lib64/libcuda.so.1 (unknown line)
unknown function (ip: 0x2aab563c4498)
unknown function (ip: 0x2aab563c4526)
unknown function (ip: 0x2aab563fa92a)
unknown function (ip: 0x2aab563b3a4a)
unknown function (ip: 0x2aab5613f45b)
unknown function (ip: 0x2aab56156795)
unknown function (ip: 0x2aab56156b8a)
unknown function (ip: 0x2aab56051241)
unknown function (ip: 0x2aab56051279)
unknown function (ip: 0x2aab560504c8)
unknown function (ip: 0x2aab56038c94)
unknown function (ip: 0x2aab56038e55)
cufftExecC2R at /usr/common/software/sles15_cgpu/cuda/10.2.89/lib64/libcufft.so.10 (unknown line)
macro expansion at /global/homes/m/marius/.julia/packages/CUDA/MpASK/lib/cufft/libcufft.jl:194 [inlined]
macro expansion at /global/homes/m/marius/.julia/packages/CUDA/MpASK/src/pool.jl:420 [inlined]
macro expansion at /global/homes/m/marius/.julia/packages/CUDA/MpASK/lib/cufft/error.jl:79 [inlined]
cufftExecC2R at /global/homes/m/marius/.julia/packages/CUDA/MpASK/lib/utils/call.jl:26
unsafe_execute! at /global/homes/m/marius/.julia/packages/CUDA/MpASK/lib/cufft/fft.jl:409 [inlined]
mul! at /global/homes/m/marius/.julia/packages/CUDA/MpASK/lib/cufft/fft.jl:462
* at /global/homes/m/marius/.julia/packages/CUDA/MpASK/lib/cufft/fft.jl:484
* at /global/homes/m/marius/.julia/packages/CUDA/MpASK/lib/cufft/fft.jl:12 [inlined]
\ at /global/homes/m/marius/.julia/packages/AbstractFFTs/JebmH/src/definitions.jl:227
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
#1 at ./threadingconstructs.jl:169
unknown function (ip: 0x2aaad9fe3cbc)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2237 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2419
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1703 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:839
unknown function (ip: (nil))
Allocations: 19087686 (Pool: 19082255; Big: 5431); GC: 15
Segmentation fault
```

I also note it sometimes triggers a CUDA OOM, so I need to manually do a `GC.gc(true); CUDA.reclaim()`. I'm not sure I've been able to trigger this before having to do that in fact.

This seems to be present on master (as well as CUDA 3.0.3):

<details>

```
  [052768ef] CUDA v3.0.3 `https://github.com/JuliaGPU/CUDA.jl.git#master`
  [0c68f7d7] GPUArrays v6.2.2
  [61eb1bfa] GPUCompiler v0.11.4
```

```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
Environment:
  JULIA_MPI_TRANSPORT = TCP
  JULIA_REVISE_POLL = 1
  JULIA_CUDA_USE_BINARYBUILDER = false
  JULIA_CUDA_MEMORY_LIMIT = 15032385536
  JULIA_MPI_BINARY = system
  JULIA_PROJECT = @.
  JULIA_NUM_THREADS = 1
  JULIA_FFTW_PROVIDER = FFTW
```

```
CUDA toolkit 10.2.89, local installation
CUDA driver 11.0.0
NVIDIA driver 450.102.4

Libraries: 
- CUBLAS: 10.2.2
- CURAND: 10.1.2
- CUFFT: 10.1.2
- CUSOLVER: 10.3.0
- CUSPARSE: 10.3.1
- CUPTI: 12.0.0
- NVML: 11.0.0+450.102.4
- CUDNN: 8.0.0 (for CUDA 10.2.0)
- CUTENSOR: missing

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

Environment:
- JULIA_CUDA_MEMORY_LIMIT: 15032385536
- JULIA_CUDA_USE_BINARYBUILDER: false

1 device:
  0: Tesla V100-SXM2-16GB (sm_70, 7.042 GiB / 15.782 GiB available)
```

**Comment by maleadt** [comment] 2021-04-23 10:46
You're creating a FFT plan `plan` and array `y` in the global task, and using that data in other tasks. That's not valid for library resources like `plan`, and to share data like `y` you need to synchronize first.

**Comment by maleadt** [comment] 2021-04-23 10:48
This probably needs a more strong warning in the 'tasks and threads' part of the documentation though.

**Comment by marius311** [comment] 2021-04-23 22:45
Hmm so can plans only be used from the task that created them? Ultimately what I want to do is something like

```julia
@assert nthreads() == length(CUDA.devices())

plans = map(1:nthreads()) do i
    device!(i)
    plan_fft(...)
end

tmap(1:nthreads()) do i
    device!(i)
    x = CuArray(...)
    plans[i] * x 
    # etc..
end
```

Basically I just want to have a set of per-device plans and then later be thread-mapping over stuff where each device uses its own plan. What would be the right way to do this?

**Comment by maleadt** [comment] 2021-04-24 07:54
Sorry, I was wrong. The handle-per-task restriction doesn't apply to CUFFT, where we use plans as handles. The problem is that the current stream is assigned to the plan upon creation, so all plans use the main task's stream. It should probably update the stream when executing the plan.

**Comment by maleadt** [comment] 2021-04-26 09:00
The PR should allow creating a plan on one stream and executing it on another.

The OOM you're seeing is because you're creating a ton of tasks, and there's how the handle cache interacts with the GC. We end up with tons of stale idles that don't get freed, resulting in the high memory usage because your MWE never triggers GC until it's too late. I'm looking into a better handle cache.

**Comment by maleadt** [comment] 2021-04-26 09:50
https://github.com/JuliaGPU/CUDA.jl/pull/868 should fix the OOM

**Closed as completed** 2021-04-27 05:42 UTC
Labels: needs documentation
