### ISSUE TITLE
unsafe_copy3d! does not work with stream-ordered allocations

### ISSUE THREAD

**Issue by omlins** [JuliaGPU/CUDA.jl#863] opened 2021-04-23 18:57 UTC
**Describe the bug**
`Mem.unsafe_copy3d!` appears to handle wrongly the `srcPos` (and maybe also `dstPos`) argument. 

**To reproduce**

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*UPDATE:*
The second comment gives a 10-line MWE; jump directly [there](https://github.com/JuliaGPU/CUDA.jl/issues/863#issuecomment-826320460)!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

The following code, which is extracted from the unit tests of [ImplicitGlobalGrid](https://github.com/eth-cscs/ImplicitGlobalGrid.jl), passes with CUDA 1, but fails with CUDA 3:
```julia
julia> using Test

julia> using ImplicitGlobalGrid; GG = ImplicitGlobalGrid
ImplicitGlobalGrid

julia> import MPI

julia> import ImplicitGlobalGrid: @require, longnameof

julia> test_gpu = GG.ENABLE_CUDA
true

julia> if test_gpu
               using CUDA
               @assert CUDA.functional(true)
               global cuzeros = CUDA.zeros
               global allocators = [zeros, cuzeros]
               global ArrayConstructors = [Array, CuArray]
       else
               global cuzeros = nothing  # To enable statements like: if zeros==cuzeros
               global allocators = [zeros]
               global ArrayConstructors = [Array]
       end
2-element Vector{UnionAll}:
 Array
 CuArray

julia> ## Test setup
       MPI.Init();

julia> nprocs = MPI.Comm_size(MPI.COMM_WORLD);

julia> ndims_mpi = GG.NDIMS_MPI;

julia> nneighbors_per_dim = GG.NNEIGHBORS_PER_DIM; # Should be 2 (one left and one right neighbor).

julia> nx = 7;

julia> ny = 5;

julia> nz = 6;

julia> dx = 1.0
1.0

julia> dy = 1.0
1.0

julia> dz = 1.0
1.0

julia> init_global_grid(nx, ny, nz, quiet=true, init_MPI=false);

julia> P  = zeros(nx,  ny,  nz  );

julia> P .= [iz*1e2 + iy*1e1 + ix for ix=1:size(P,1), iy=1:size(P,2), iz=1:size(P,3)];

julia> P  = CuArray(P);

julia> # (dim=2)
                                              dim = 2;

julia> P2  = cuzeros(eltype(P),size(P));

julia> buf = zeros(size(P,1), size(P,3));

julia> buf_d, buf_h = GG.register(buf);

julia> ranges = [1:size(P,1), 3:3, 1:size(P,3)];

julia> nthreads = (1, 1, 1);

julia> halosize = [r[end] - r[1] + 1 for r in ranges];

julia> nblocks  = Tuple(ceil.(Int, halosize./nthreads));

julia> ranges
3-element Vector{UnitRange{Int64}}:
 1:7
 3:3
 1:6

julia> custream = CuDefaultStream();

julia> sendbuf=buf; A=P; sendranges=ranges; T=Float64;

julia> Mem.unsafe_copy3d!(
                   pointer(sendbuf), Mem.Host, pointer(A), Mem.Device,
                   length(sendranges[1]), length(sendranges[2]), length(sendranges[3]);
                   srcPos=(sendranges[1][1], sendranges[2][1], sendranges[3][1]),
                   srcPitch=sizeof(T)*size(A,1), srcHeight=size(A,2),
                   dstPitch=sizeof(T)*length(sendranges[1]), dstHeight=length(sendranges[2]),
                   async=true, stream=custream
               )  # GG.write_d2h_async!(buf, P, ranges, dim, custream); 
julia> CUDA.synchronize();

julia> @test all(buf[:] .== Array(P[ranges[1],ranges[2],ranges[3]][:]))
Test Failed at REPL[40]:1
  Expression: all(buf[:] .== Array((P[ranges[1], ranges[2], ranges[3]])[:]))
ERROR: There was an error during testing

julia> ranges
3-element Vector{UnitRange{Int64}}:
 1:7
 3:3
 1:6

julia> buf
7×6 Matrix{Float64}:
 111.0  211.0  311.0  411.0  511.0  611.0
 112.0  212.0  312.0  412.0  512.0  612.0
 113.0  213.0  313.0  413.0  513.0  613.0
 114.0  214.0  314.0  414.0  514.0  614.0
 115.0  215.0  315.0  415.0  515.0  615.0
 116.0  216.0  316.0  416.0  516.0  616.0
 117.0  217.0  317.0  417.0  517.0  617.0
```

For comparison here is the buffer of a successful test with an equivalent function in terms of functionality (but not performance):
```julia
julia> buf .= 0.0;

julia> P2  .= 0.0;

julia> @cuda blocks=nblocks threads=nthreads GG.write_d2x!(buf_d, P, ranges[1], ranges[2], ranges[3], dim); CUDA.synchronize();

julia> @test all(buf[:] .== Array(P[ranges[1],ranges[2],ranges[3]][:]))
Test Passed

julia> @cuda blocks=nblocks threads=nthreads GG.read_x2d!(buf_d, P2, ranges[1], ranges[2], ranges[3], dim); CUDA.synchronize();

julia> @test all(buf[:] .== Array(P2[ranges[1],ranges[2],ranges[3]][:]))
Test Passed

julia> buf
7×6 Matrix{Float64}:
 131.0  231.0  331.0  431.0  531.0  631.0
 132.0  232.0  332.0  432.0  532.0  632.0
 133.0  233.0  333.0  433.0  533.0  633.0
 134.0  234.0  334.0  434.0  534.0  634.0
 135.0  235.0  335.0  435.0  535.0  635.0
 136.0  236.0  336.0  436.0  536.0  636.0
 137.0  237.0  337.0  437.0  537.0  637.0

```

This example shows that the `srcPos` is not correctly dealt with. The result is that the XZ-plane at position  y=1 is copied into the buffer instead of the one at position y=3.

**Version info**

Details on Julia:

```julia
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_CUDA_USE_BINARYBUILDER = false
  JULIA_MPI_BINARY = system
  JULIA_MPI_PATH = /opt/cray/pe/mpt/7.7.15/gni/mpich-gnu/8.2
  JULIA_MPIEXEC = srun
  JULIA_MPICC = cc
  JULIA_MPIEXEC_ARGS = -C gpu

```

Details on CUDA:

```julia
julia> CUDA.versioninfo()
CUDA toolkit 11.0.2, local installation
CUDA driver 11.2.0
NVIDIA driver 460.27.4

Libraries: 
- CUBLAS: 11.1.0
- CURAND: 10.2.1
- CUFFT: 10.2.0
- CUSOLVER: 10.5.0
- CUSPARSE: 11.1.0
- CUPTI: 13.0.0
- NVML: 11.0.0+460.27.4
- CUDNN: missing
- CUTENSOR: missing

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5, 7.0
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75, sm_80

Environment:
- JULIA_CUDA_USE_BINARYBUILDER: false

1 device:
  0: Tesla P100-PCIE-16GB (sm_60, 15.511 GiB / 15.899 GiB available)

```

**Comment by omlins** [comment] 2021-04-25 12:58
MWE without ImplicitGlobalGrid, only CUDA:
```julia
using CUDA, Test
nx, ny, nz = 4, 4, 4
custream = CuDefaultStream();
############
## X-Z-plane
A = zeros(Float64, nx, nz);
B = CUDA.rand(Float64, nx, ny, nz);
# Copy from device to host.
Mem.unsafe_copy3d!(
           pointer(A), Mem.Host, pointer(B), Mem.Device,
           nx, 1, nz; 
           srcPos=(1,3,1),
           srcPitch=nx*sizeof(A[1]), srcHeight=ny,
           dstPitch=nx*sizeof(A[1]), dstHeight=1,
           async=true, stream=custream
       )
CUDA.synchronize();

@test all(B[:,3,:] .== CuArray(A))
```

**Comment by omlins** [comment] 2021-04-25 13:01
The MWE succeeds with CUDA 1.3.3 and CUDA 2.4.3 (using julia 1.5.2) and  CUDA 2.5.0 and CUDA 2.6.3 (using julia 1.6.0):
```
omlins@nid00000:~> julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.2 (2020-09-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using CUDA, Test

julia> nx, ny, nz = 4, 4, 4
(4, 4, 4)

julia> custream = CuDefaultStream();

julia> A = zeros(Float64, nx, nz);

julia> B = CUDA.rand(Float64, nx, ny, nz);

julia> Mem.unsafe_copy3d!(
                  pointer(A), Mem.Host, pointer(B), Mem.Device,
                  nx, 1, nz; 
                  srcPos=(1,3,1),
                  srcPitch=nx*sizeof(A[1]), srcHeight=ny,
                  dstPitch=nx*sizeof(A[1]), dstHeight=1,
                  async=true, stream=custream
              )

julia> CUDA.synchronize();

julia> @show A
A = [0.8923504176138279 0.06670585802684864 0.6517209531470487 0.32960130176173935; 0.6482025108419349 0.08613595245957256 0.14589241860603913 0.5990137923264873; 0.5439438916383488 0.6906187236255683 0.2991765182754866 0.18442897532282015; 0.7937400429081227 0.44507082959458427 0.7235666896115598 0.2889390025916862]

4×4 Array{Float64,2}:
 0.89235   0.0667059  0.651721  0.329601
 0.648203  0.086136   0.145892  0.599014
 0.543944  0.690619   0.299177  0.184429
 0.79374   0.445071   0.723567  0.288939

julia> @test all(B[:,3,:] .== CuArray(A))

Test Passed

julia> 
```

**Comment by omlins** [comment] 2021-04-25 13:05
but fails with CUDA 3.0.0 and CUDA 3.0.3 (using Julia 1.6.0):
```
omlins@nid00000:~/.julia/dev/ImplicitGlobalGrid/test> julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using CUDA, Test

julia> nx, ny, nz = 4, 4, 4
(4, 4, 4)

julia> custream = CuDefaultStream();

julia> ############
       ## X-Z-plane
       A = zeros(Float64, nx, nz);

julia> B = CUDA.rand(Float64, nx, ny, nz);

julia> Mem.unsafe_copy3d!(
                  pointer(A), Mem.Host, pointer(B), Mem.Device,
                  nx, 1, nz; 
                  srcPos=(1,3,1),
                  srcPitch=nx*sizeof(A[1]), srcHeight=ny,
                  dstPitch=nx*sizeof(A[1]), dstHeight=1,
                  async=true, stream=custream
              )
Ptr{Float64} @0x00002aab1858b860

julia> CUDA.synchronize();

julia> @show A
A = [0.10933715184287834 0.10695878144143062 0.6626231470216615 0.24015583567058202; 0.2651065286739565 0.7054441193398402 0.4348791854686909 0.023319462998272422; 0.7966447314754332 0.7691320960719457 0.19791760770606687 0.5236155573577657; 0.42375300341377015 0.12323280594363267 0.5927200491274549 0.5855023357435638]
4×4 Matrix{Float64}:
 0.109337  0.106959  0.662623  0.240156
 0.265107  0.705444  0.434879  0.0233195
 0.796645  0.769132  0.197918  0.523616
 0.423753  0.123233  0.59272   0.585502

julia> @test all(B[:,3,:] .== CuArray(A))
Test Failed at REPL[9]:1
  Expression: all(B[:, 3, :] .== CuArray(A))
ERROR: There was an error during testing
```
It wrongly copies the plane at y=1 instead of y=3:
```
julia> @test all(B[:,1,:] .== CuArray(A))
Test Passed
```

**Comment by omlins** [comment] 2021-04-25 17:01
@maleadt , the bug appears to be introduced with CUDA 3.0.0. Do you see where?

**Comment by maleadt** [comment] 2021-04-26 15:02
I'll have a look. FYI, if you have a good reproducer like this, it's fairly easy to bisect this using Git (because CUDA.jl has a committed Manifest that guarantees a functional set-up).

Also, your use of streams here is now invalid, because CUDA.jl uses its own task-local streams. That means `A` and `B` are allocated asynchronously on that task-local stream, while you're performing a `memcpy3d` using another, unrelated stream. So you should probably just use CUDA.jl's stream, `stream()`, or make sure everything is synchronized before and after using your custom stream. See https://juliagpu.org/post/2021-04-09-cuda_3.0/

**Comment by maleadt** [comment] 2021-04-26 15:47
Further reduced:

```julia
using CUDA

function main()
    nx, ny, nz = 1, 2, 1

    A = zeros(Int, nx, nz)
    B = CuArray(reshape([1:(nx*ny*nz)...], (nx, ny, nz)))
    Mem.unsafe_copy3d!(
            pointer(A), Mem.Host, pointer(B), Mem.Device,
            nx, 1, nz;
            srcPos=(1,2,1),
            srcPitch=nx*sizeof(A[1]), srcHeight=ny,
            dstPitch=nx*sizeof(A[1]), dstHeight=1
        )

    println(Array(B)[:,2,:])
    println(Array(A))
end

main()
```

Bisected to 54ed839880b4c979a2d04cea764e35eb0f9f59db, although this doesn't look like a CUDA.jl issue, but might be a CUDA.jl bug.  No matter how much calls to `device_synchronize()` I add, the results remain wrong. However, switching back to the old synchronous allocator by setting `JULIA_CUDA_MEMORY_POOL=none` makes the issue disappear. Looking at API traces, nothing seems off either:

Asynchronous allocation:
```
julia> main()
cuMemAllocAsync(Base.RefValue{CuPtr{Nothing}}, 16, CuStream(0x000000000574bd40, CuContext(0x000000000470bec0, instance 1e4304cb0a8163c3))) = CUDA_SUCCESS
 1: CuPtr{Nothing}(0x0000000302001000)
cuMemcpyHtoDAsync_v2(CuPtr{Int64}(0x0000000302001000), Ptr{Int64} @0x00007f12cad6c2f0, 16, CuStream(0x000000000574bd40, CuContext(0x000000000470bec0, instance 1e4304cb0a8163c3))) = CUDA_SUCCESS
cuMemcpy3DAsync_v2(Base.RefValue{CUDA.CUDA_MEMCPY3D_st}, CuStream(0x000000000574bd40, CuContext(0x000000000470bec0, instance 1e4304cb0a8163c3))) = CUDA_SUCCESS
 1: CUDA.CUDA_MEMCPY3D_st(0x0000000000000000, 0x0000000000000001, 0x0000000000000000, 0x0000000000000000, CUDA.CU_MEMORYTYPE_DEVICE, Ptr{Nothing} @0x0000000000000000, CuPtr{Nothing}(0x0000000302001000), CuArrayPtr{Nothing}(0x0000000000000000), Ptr{Nothing} @0x0000000000000000, 0x0000000000000008, 0x0000000000000002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, CUDA.CU_MEMORYTYPE_HOST, Ptr{Nothing} @0x00007f12cad67c50, CuPtr{Nothing}(0x0000000000000000), CuArrayPtr{Nothing}(0x0000000000000000), Ptr{Nothing} @0x0000000000000000, 0x0000000000000008, 0x0000000000000001, 0x0000000000000008, 0x0000000000000001, 0x0000000000000001)
cuMemcpyDtoHAsync_v2(Ptr{Int64} @0x00007f12cc047710, CuPtr{Int64}(0x0000000302001000), 16, CuStream(0x000000000574bd40, CuContext(0x000000000470bec0, instance 1e4304cb0a8163c3))) = CUDA_SUCCESS
cuCtxSynchronize() = CUDA_SUCCESS
1×1 Matrix{Int64}:
 2
1×1 Matrix{Int64}:
 1
```

Synchronous allocation:
```
julia> main()
cuMemAlloc_v2(Base.RefValue{CuPtr{Nothing}}, 16) = CUDA_SUCCESS
 1: CuPtr{Nothing}(0x00007f11d5a00800)
cuMemcpyHtoDAsync_v2(CuPtr{Int64}(0x00007f11d5a00800), Ptr{Int64} @0x00007f12cc08adb0, 16, CuStream(0x000000000574bd40, CuContext(0x000000000470bec0, instance 1e4304cb0a8163c3))) = CUDA_SUCCESS
cuMemcpy3DAsync_v2(Base.RefValue{CUDA.CUDA_MEMCPY3D_st}, CuStream(0x000000000574bd40, CuContext(0x000000000470bec0, instance 1e4304cb0a8163c3))) = CUDA_SUCCESS
 1: CUDA.CUDA_MEMCPY3D_st(0x0000000000000000, 0x0000000000000001, 0x0000000000000000, 0x0000000000000000, CUDA.CU_MEMORYTYPE_DEVICE, Ptr{Nothing} @0x0000000000000000, CuPtr{Nothing}(0x00007f11d5a00800), CuArrayPtr{Nothing}(0x0000000000000000), Ptr{Nothing} @0x0000000000000000, 0x0000000000000008, 0x0000000000000002, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000, CUDA.CU_MEMORYTYPE_HOST, Ptr{Nothing} @0x00007f12cc08ad50, CuPtr{Nothing}(0x0000000000000000), CuArrayPtr{Nothing}(0x0000000000000000), Ptr{Nothing} @0x0000000000000000, 0x0000000000000008, 0x0000000000000001, 0x0000000000000008, 0x0000000000000001, 0x0000000000000001)
cuMemcpyDtoHAsync_v2(Ptr{Int64} @0x00007f12d37a9a30, CuPtr{Int64}(0x00007f11d5a00800), 16, CuStream(0x000000000574bd40, CuContext(0x000000000470bec0, instance 1e4304cb0a8163c3))) = CUDA_SUCCESS
cuCtxSynchronize() = CUDA_SUCCESS
1×1 Matrix{Int64}:
 2
1×1 Matrix{Int64}:
 2
```

I'm going to file this with NVIDIA, let's hope we're doing something wrong or that there's a workaround that doesn't involve disabling the stream-ordered allocator.

EDIT: reported as NVIDIA bug #3299813.

**Comment by omlins** [comment] 2021-04-28 09:55
@maleadt , I can confirm your observations: 
1) calls to `CUDA.device_synchronize()` do **not** make the issue disappear, 
2) setting `JULIA_CUDA_MEMORY_POOL=none` or `JULIA_CUDA_MEMORY_POOL=binned` makes the issue disappear.

All these tests were done on our TDS with the CUDA toolkit 11 installed as reported in the issue description. I do **not** observe this issue on Piz Daint, where there is still CUDA toolkit 10 installed:
```julia
julia> CUDA.versioninfo()
CUDA toolkit 10.2.89, local installation
CUDA driver 11.0.0
NVIDIA driver 450.51.5

Libraries: 
- CUBLAS: 10.2.2
- CURAND: 10.1.2
- CUFFT: 10.1.2
- CUSOLVER: 10.3.0
- CUSPARSE: 10.3.1
- CUPTI: 12.0.0
- NVML: 11.0.0+450.51.5
- CUDNN: missing
- CUTENSOR: missing

Toolchain:
- Julia: 1.6.0
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5
- Device support: sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

Environment:
- JULIA_CUDA_USE_BINARYBUILDER: false

1 device:
  0: Tesla P100-PCIE-16GB (sm_60, 15.605 GiB / 15.899 GiB available)
```

Thus, it looks to me as well like a bug in CUDA's stream-ordered allocator (in combination with 3D memcopies) as you noted in the slack channel.


I furthermore observed that with CUDA toolkit 11 (on the TDS system), the issue occurs also with CUDA 2.4.3 (last CUDA 2 for Julia 1.5) and CUDA  2.0.0, and all versions in between presumably. However, the issue does **not** occur with CUDA 2.6.3 (last CUDA 2 for Julia 1.6).
@maleadt , can you explain this behaviour? Does CUDA 2.0.0-2.4.3 already use the new stream-ordered allocators if CUDA toolkit 11 is available? What about CUDAa 2.6.3?

**Comment by maleadt** [comment] 2021-04-28 09:58
See https://github.com/JuliaGPU/CUDA.jl/pull/872 where I pinged you. The issue has been triaged and worked around.

EDIT: I responded too quickly:



> I furthermore observed that with CUDA toolkit 11 (on the TDS system), the issue occurs also with CUDA 2.4.3 (last CUDA 2 for Julia 1.5) and CUDA 2.0.0, and all versions in between presumably. However, the issue does **not** occur with CUDA 2.6.3 (last CUDA 2 for Julia 1.6).

That's... interesting. Are you sure it's the same issue? The stream-ordered allocator is only used by CUDA.jl 3.0 on CUDA 11.2 or newer.

**Comment by omlins** [comment] 2021-04-28 10:02
Yes, I just saw it thanks!
If it is the same issue, I don`t know. But setting JULIA_CUDA_MEMORY_POOL=binned (or probably also JULIA_CUDA_MEMORY_POOL=none) makes the issue disappear.

**Comment by maleadt** [comment] 2021-04-28 10:40
> setting JULIA_CUDA_MEMORY_POOL=binned (or probably also JULIA_CUDA_MEMORY_POOL=none) makes the issue disappear

I don't think that's possible, as the binned pool was the default up until CUDA 3.0. Are you sure you're actually testing CUDA 2.4.3?

**Comment by omlins** [comment] 2021-04-28 10:47
Indeed, with CUDA 2.4.3, the issue does not appear to be the same, the MWEs succeed without setting JULIA_CUDA_MEMORY_POOL:
```julia
omlins@nid00002:~> echo $JULIA_CUDA_MEMORY_POOL

omlins@nid00002:~> julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.2 (2020-09-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.5) pkg> status
Status `~/.julia/environments/v1.5/Project.toml`
  [052768ef] CUDA v2.4.3
  [4d7a3746] ImplicitGlobalGrid v0.10.1 `~/.julia/dev/ImplicitGlobalGrid`
  [da04e1cc] MPI v0.16.1

julia> using CUDA

julia> function main()
           nx, ny, nz = 1, 2, 1

           A = zeros(Int, nx, nz)
           B = CuArray(reshape([1:(nx*ny*nz)...], (nx, ny, nz)))
           Mem.unsafe_copy3d!(
                   pointer(A), Mem.Host, pointer(B), Mem.Device,
                   nx, 1, nz;
                   srcPos=(1,2,1),
                   srcPitch=nx*sizeof(A[1]), srcHeight=ny,
                   dstPitch=nx*sizeof(A[1]), dstHeight=1
               )

           println(Array(B)[:,2,:])
           println(Array(A))
       end
main (generic function with 1 method)

julia> main()
[2]
[2]

julia> using CUDA, Test

julia> nx, ny, nz = 4, 4, 4
(4, 4, 4)

julia> custream = CuDefaultStream();

julia> ############
       ## X-Z-plane
       A = zeros(Float64, nx, nz);

julia> B = CUDA.rand(Float64, nx, ny, nz);

julia> # Copy from device to host.
       Mem.unsafe_copy3d!(
                  pointer(A), Mem.Host, pointer(B), Mem.Device,
                  nx, 1, nz; 
                  srcPos=(1,3,1),
                  srcPitch=nx*sizeof(A[1]), srcHeight=ny,
                  dstPitch=nx*sizeof(A[1]), dstHeight=1,
                  async=true, stream=custream
              )

julia> CUDA.synchronize();

julia> @test all(B[:,3,:] .== CuArray(A))
Test Passed

julia> 
```

**Closed as completed** 2021-04-28 14:20 UTC
Labels: cuda array, upstream, regression
